# Appendix 2: Python Libraries Crash Course

## Part 3: Multi-Dimensional Numpy Arrays

### Nested Lists

In [1]:
project_1 = [-200, 20, 50, 70, 100, 50]
project_2 = [-50, 10, 25, 25, 50]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [2]:
all_proj = [project_1, project_2, project_3]

In [3]:
all_proj

[[-200, 20, 50, 70, 100, 50],
 [-50, 10, 25, 25, 50],
 [-1000, 200, 200, 300, 500, 500, 750, 250]]

In [4]:
type(all_proj)

list

In [5]:
len(all_proj)

3

In [6]:
all_proj[0]

[-200, 20, 50, 70, 100, 50]

In [7]:
all_proj[2]

[-1000, 200, 200, 300, 500, 500, 750, 250]

In [8]:
all_proj[-1]

[-1000, 200, 200, 300, 500, 500, 750, 250]

In [9]:
all_proj[:2]

[[-200, 20, 50, 70, 100, 50], [-50, 10, 25, 25, 50]]

In [10]:
all_proj[-2:]

[[-50, 10, 25, 25, 50], [-1000, 200, 200, 300, 500, 500, 750, 250]]

In [ ]:
all_proj[0][0]

In [13]:
all_proj[:]

[[-200, 20, 50, 70, 100, 50],
 [-50, 10, 25, 25, 50],
 [-1000, 200, 200, 300, 500, 500, 750, 250]]

In [12]:
all_proj[:][0]

[-200, 20, 50, 70, 100, 50]

In [14]:
I0 = []
for proj in all_proj:
    I0.append(proj[0])

In [15]:
I0

[-200, -50, -1000]

### 2-dim Numpy Arrays

In [16]:
import numpy as np

In [17]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]
nl = [cf1, cf2, cf3]

In [18]:
nl

[[-200, 20, 50, 70, 100, 50],
 [-150, 25, 60, 50, 50, 40],
 [-250, 10, 25, 50, 125, 200]]

In [19]:
np.array(nl)

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [20]:
cfs = np.array(nl)

In [21]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [22]:
type(cfs)

numpy.ndarray

In [23]:
cfs.shape

(3, 6)

In [24]:
cfs[0]

array([-200,   20,   50,   70,  100,   50])

In [25]:
cfs[-1]

array([-250,   10,   25,   50,  125,  200])

In [26]:
cfs[1:]

array([[-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [27]:
cfs[0][0]

-200

In [28]:
cfs[0, 0]

-200

### Slicing 2-dim Numpy Arrays (Part 1)

In [29]:
import numpy as np

In [30]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [31]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [32]:
cfs.shape

(3, 6)

In [33]:
cfs[:, 0]

array([-200, -150, -250])

In [34]:
cfs[:, -1]

array([ 50,  40, 200])

In [35]:
cfs[:, :2]

array([[-200,   20],
       [-150,   25],
       [-250,   10]])

In [36]:
cfs[2, 1:]

array([ 10,  25,  50, 125, 200])

In [37]:
cfs[-2:, :2]

array([[-150,   25],
       [-250,   10]])

In [38]:
project_1 = [-200, 20, 50, 70, 100, 50]
project_2 = [-50, 10, 25, 25, 50]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [40]:
array = np.array([project_1, project_2, project_3], dtype=object)

In [41]:
array

array([list([-200, 20, 50, 70, 100, 50]), list([-50, 10, 25, 25, 50]),
       list([-1000, 200, 200, 300, 500, 500, 750, 250])], dtype=object)

In [42]:
array.shape

(3,)

In [43]:
# array[:, 0]

In [44]:
project_1 = np.array([-200, 20, 50, 70, 100, 50, 0, 0])
project_2 = np.array([-50, 10, 25, 25, 50, 0, 0, 0])
project_3 = np.array([-1000, 200, 200, 300, 500, 500, 750, 250])

In [45]:
projects = np.array([project_1, project_2, project_3])

In [46]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [47]:
projects.shape

(3, 8)

In [48]:
projects[:, 0]

array([ -200,   -50, -1000])

In [49]:
project_1 = np.array([-200, 20, 50, 70, 100, 50])

In [50]:
project_1.resize(8)

In [51]:
project_1

array([-200,   20,   50,   70,  100,   50,    0,    0])

### Slicing 2-dim Numpy Arrays (Part 2)

In [52]:
import numpy as np

In [53]:
cf1 = np.array([-200, 20, 50, 70, 100, 50])
cf2 = np.array([-150, 25, 60, 50, 50, 40])
cf3 = np.array([-250, 10, 25, 50, 125, 200])

In [54]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [55]:
cf1[[0, 3, -1]]

array([-200,   70,   50])

In [56]:
cfs[[0,-1], 0]

array([-200, -250])

In [57]:
cfs[0, [0, 2, -1]]

array([-200,   50,   50])

### Recap: Changing Elements in a Numpy Array / slice

In [58]:
import numpy as np

In [59]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [60]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [61]:
cfs[:, 0] = -200

In [62]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-200,   25,   60,   50,   50,   40],
       [-200,   10,   25,   50,  125,  200]])

In [63]:
cfs[:, 0] = cfs[:, 0] - 10

In [64]:
cfs

array([[-210,   20,   50,   70,  100,   50],
       [-210,   25,   60,   50,   50,   40],
       [-210,   10,   25,   50,  125,  200]])

In [65]:
cfs[:, 0] = [-200, -150, -250]

In [66]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [67]:
I0s = cfs[:, 0]
I0s

array([-200, -150, -250])

In [68]:
I0s[0] = -180
I0s

array([-180, -150, -250])

In [69]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [70]:
cf5 = cfs[:, -1].copy()
cf5

array([ 50,  40, 200])

In [71]:
cf5[-1] = 150
cf5

array([ 50,  40, 150])

In [72]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

### Row- and Column wise operations

In [73]:
import numpy as np
np.set_printoptions(precision=2, suppress= True)

In [74]:
project_1 = [-200, 20, 50, 70, 100, 50, 0, 0]
project_2 = [-50, 10, 25, 25, 50, 0, 0, 0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [75]:
projects = np.array([project_1, project_2, project_3])

In [76]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [77]:
np.sum(projects)

1850

In [78]:
np.sum(projects, axis = 0)

array([-1250,   230,   275,   395,   650,   550,   750,   250])

In [79]:
np.sum(projects, axis = 1)

array([  90,   60, 1700])

In [80]:
np.cumsum(projects, axis = 1)

array([[ -200,  -180,  -130,   -60,    40,    90,    90,    90],
       [  -50,   -40,   -15,    10,    60,    60,    60,    60],
       [-1000,  -800,  -600,  -300,   200,   700,  1450,  1700]],
      dtype=int32)

In [81]:
np.cumsum(projects, axis = 0)

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [ -250,    30,    75,    95,   150,    50,     0,     0],
       [-1250,   230,   275,   395,   650,   550,   750,   250]],
      dtype=int32)

In [82]:
np.mean(projects, axis = 1)

array([ 11.25,   7.5 , 212.5 ])

In [83]:
np.mean(projects, axis = 0)

array([-416.67,   76.67,   91.67,  131.67,  216.67,  183.33,  250.  ,
         83.33])

In [ ]:
np.mean(projects, axis = 0)

In [ ]:
np.mean(projects)